export type Challenge = {
  id: string;
  city: string; // which city this applies to, or "Any"
  title: string;
  description: string;
  difficulty: "easy" | "medium" | "hard" | "legendary";
  points: number; // 10, 25, 50, 100
  category: "food" | "social" | "adventure" | "culture" | "dare";
};

export const DAILY_CHALLENGES: Challenge[] = [
  // ── Boston (Jun 11-13) ────────────────────────────────────────────────────
  {
    id: "bos-chowdah",
    city: "Boston",
    title: "Chowdah Time",
    description: 'Order a "chowdah" with a Boston accent',
    difficulty: "easy",
    points: 10,
    category: "food",
  },
  {
    id: "bos-freedom-trail",
    city: "Boston",
    title: "Freedom Trail Walker",
    description: "Walk the Freedom Trail (at least 3 stops)",
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "bos-lobster-battle",
    city: "Boston",
    title: "Lobster Roll Showdown",
    description: "Try a lobster roll from both a tourist spot AND a local spot",
    difficulty: "hard",
    points: 50,
    category: "food",
  },
  {
    id: "bos-go-sox",
    city: "Boston",
    title: "Go Sox!",
    description: 'Yell "Go Sox!" in a crowded bar',
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "bos-cheers",
    city: "Boston",
    title: "Where Everybody Knows Your Name",
    description: "Find and photograph all 3 of you at the Cheers bar",
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "bos-sam-adams",
    city: "Boston",
    title: "Sam Adams Pilgrimage",
    description: "Visit the Sam Adams brewery and try a flight",
    difficulty: "medium",
    points: 25,
    category: "food",
  },
  {
    id: "bos-fenway",
    city: "Boston",
    title: "Fenway Faithful",
    description: "Take a selfie outside Fenway Park",
    difficulty: "easy",
    points: 10,
    category: "culture",
  },
  {
    id: "bos-accent",
    city: "Boston",
    title: "Pahk the Cah",
    description: "Maintain a Boston accent for an entire conversation with a local",
    difficulty: "hard",
    points: 50,
    category: "dare",
  },

  // ── New York (Jun 13-15) ──────────────────────────────────────────────────
  {
    id: "nyc-dollar-slice",
    city: "New York",
    title: "Dollar Slice",
    description: "Eat a dollar slice of pizza",
    difficulty: "easy",
    points: 10,
    category: "food",
  },
  {
    id: "nyc-brooklyn-bridge",
    city: "New York",
    title: "Bridge the Gap",
    description: "Walk across the Brooklyn Bridge",
    difficulty: "medium",
    points: 25,
    category: "adventure",
  },
  {
    id: "nyc-speakeasy",
    city: "New York",
    title: "Speakeasy Secret",
    description: "Get into a speakeasy bar",
    difficulty: "hard",
    points: 50,
    category: "adventure",
  },
  {
    id: "nyc-subway-stranger",
    city: "New York",
    title: "Subway Social",
    description: "Talk to a stranger on the subway",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "nyc-walking-here",
    city: "New York",
    title: "I'm Walkin' Here!",
    description:
      'Take a photo recreating the "I\'m walking here!" Midnight Cowboy scene',
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "nyc-football-convert",
    city: "New York",
    title: "Beautiful Game Evangelist",
    description:
      "Convince a New Yorker that football (soccer) is better than baseball",
    difficulty: "legendary",
    points: 100,
    category: "social",
  },
  {
    id: "nyc-bagel",
    city: "New York",
    title: "Bagel Boss",
    description: "Try a proper NYC bagel from a deli before 9am",
    difficulty: "easy",
    points: 10,
    category: "food",
  },
  {
    id: "nyc-times-square",
    city: "New York",
    title: "Times Square Tourist",
    description: "Survive Times Square and take the most tourist photo possible",
    difficulty: "easy",
    points: 10,
    category: "culture",
  },

  // ── Philadelphia (Jun 15-17) ──────────────────────────────────────────────
  {
    id: "phi-cheesesteak",
    city: "Philadelphia",
    title: "Whiz Wit!",
    description: "Eat a Philly cheesesteak (Whiz wit!)",
    difficulty: "easy",
    points: 10,
    category: "food",
  },
  {
    id: "phi-rocky-steps",
    city: "Philadelphia",
    title: "Rocky Run",
    description: "Run the Rocky steps at Philadelphia Museum of Art",
    difficulty: "medium",
    points: 25,
    category: "adventure",
  },
  {
    id: "phi-pats-vs-genos",
    city: "Philadelphia",
    title: "The Great Steak Debate",
    description:
      "Try BOTH Pat's and Geno's cheesesteaks, declare a winner",
    difficulty: "hard",
    points: 50,
    category: "food",
  },
  {
    id: "phi-rocky-stranger",
    city: "Philadelphia",
    title: "Rocky Pose",
    description: "Do the Rocky pose at the top of the steps with a stranger",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "phi-liberty-bell",
    city: "Philadelphia",
    title: "Liberty Selfie",
    description:
      "Ring the Liberty Bell. Just kidding, try to get a selfie as close as possible",
    difficulty: "legendary",
    points: 100,
    category: "culture",
  },
  {
    id: "phi-iggles",
    city: "Philadelphia",
    title: "Go Birds!",
    description: "Wear an Eagles jersey or say 'Go Birds!' to a local and get a reaction",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "phi-pretzel",
    city: "Philadelphia",
    title: "Pretzel City",
    description: "Try a soft pretzel from a street vendor with mustard",
    difficulty: "easy",
    points: 10,
    category: "food",
  },

  // ── Washington DC (Jun 17-19) ─────────────────────────────────────────────
  {
    id: "dc-lincoln",
    city: "Washington DC",
    title: "Honest Abe",
    description: "Take a selfie at the Lincoln Memorial",
    difficulty: "easy",
    points: 10,
    category: "culture",
  },
  {
    id: "dc-smithsonian-5",
    city: "Washington DC",
    title: "Museum Marathon",
    description: "Visit 5 Smithsonian museums in one day (all free!)",
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "dc-spot-politician",
    city: "Washington DC",
    title: "Politician Spotter",
    description: "Spot a senator or congressman in the wild",
    difficulty: "hard",
    points: 50,
    category: "adventure",
  },
  {
    id: "dc-american-accent",
    city: "Washington DC",
    title: "When in Rome...",
    description: "Do an American accent for an entire meal",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "dc-british-embassy",
    city: "Washington DC",
    title: "Home Away from Home",
    description: "Find the British Embassy and take a photo outside",
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "dc-mall-walk",
    city: "Washington DC",
    title: "National Mall Trek",
    description: "Walk the entire National Mall from Capitol to Lincoln Memorial",
    difficulty: "medium",
    points: 25,
    category: "adventure",
  },
  {
    id: "dc-spy-museum",
    city: "Washington DC",
    title: "Secret Agent",
    description: "Visit the International Spy Museum and complete a cover identity",
    difficulty: "medium",
    points: 25,
    category: "culture",
  },

  // ── Nashville (Jun 19-22) ─────────────────────────────────────────────────
  {
    id: "nas-line-dance",
    city: "Nashville",
    title: "Honky-Tonk Hero",
    description: "Line dance at a honky-tonk",
    difficulty: "easy",
    points: 10,
    category: "social",
  },
  {
    id: "nas-hot-chicken",
    city: "Nashville",
    title: "Fire Breather",
    description:
      "Survive Nashville hot chicken at Prince's (medium heat or above)",
    difficulty: "medium",
    points: 25,
    category: "food",
  },
  {
    id: "nas-open-mic",
    city: "Nashville",
    title: "Broadway Star",
    description: "Get on stage at an open mic night on Broadway",
    difficulty: "hard",
    points: 50,
    category: "dare",
  },
  {
    id: "nas-cowboy-hat",
    city: "Nashville",
    title: "Hat's On",
    description: "Wear a cowboy hat for an entire day",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "nas-country-song",
    city: "Nashville",
    title: "Nashville Songwriter",
    description: "Write and perform a country song about the road trip",
    difficulty: "legendary",
    points: 100,
    category: "culture",
  },
  {
    id: "nas-loveless-biscuit",
    city: "Nashville",
    title: "Biscuit Bliss",
    description: "Try a biscuit from Loveless Cafe",
    difficulty: "medium",
    points: 25,
    category: "food",
  },
  {
    id: "nas-pedal-tavern",
    city: "Nashville",
    title: "Pedal Power",
    description: "Ride a pedal tavern down Broadway",
    difficulty: "medium",
    points: 25,
    category: "adventure",
  },
  {
    id: "nas-boot-shop",
    city: "Nashville",
    title: "These Boots",
    description: "Try on cowboy boots at a boot shop on Broadway",
    difficulty: "easy",
    points: 10,
    category: "adventure",
  },

  // ── Miami (Jun 22-26) ─────────────────────────────────────────────────────
  {
    id: "mia-cafecito",
    city: "Miami",
    title: "Cafecito Culture",
    description: "Order a Cuban coffee (cafecito)",
    difficulty: "easy",
    points: 10,
    category: "food",
  },
  {
    id: "mia-welcome-sign",
    city: "Miami",
    title: "Welcome to Miami",
    description: 'Take a photo at the "Welcome to Miami" sign',
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "mia-salsa",
    city: "Miami",
    title: "Salsa Kings",
    description: "Dance salsa at a Latin club",
    difficulty: "hard",
    points: 50,
    category: "adventure",
  },
  {
    id: "mia-spanish-meal",
    city: "Miami",
    title: "Hablamos Espanol",
    description: "Order an entire meal in Spanish",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "mia-little-havana",
    city: "Miami",
    title: "Little Havana Explorer",
    description: "Explore Little Havana, try a cigar",
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "mia-ocean-clothed",
    city: "Miami",
    title: "Victory Plunge",
    description: "Jump into the ocean fully clothed after a match",
    difficulty: "legendary",
    points: 100,
    category: "dare",
  },
  {
    id: "mia-art-deco",
    city: "Miami",
    title: "Art Deco Walk",
    description: "Walk Ocean Drive and photograph 5 Art Deco buildings",
    difficulty: "medium",
    points: 25,
    category: "culture",
  },
  {
    id: "mia-cuban-sandwich",
    city: "Miami",
    title: "Sandwich Cubano",
    description: "Eat an authentic Cuban sandwich in Little Havana",
    difficulty: "easy",
    points: 10,
    category: "food",
  },

  // ── Any City ──────────────────────────────────────────────────────────────
  {
    id: "any-group-selfie",
    city: "Any",
    title: "Squad Snap",
    description: "Take a group selfie with a stranger",
    difficulty: "easy",
    points: 10,
    category: "social",
  },
  {
    id: "any-craft-beer",
    city: "Any",
    title: "Craft Connoisseur",
    description: "Try a local craft beer in every city",
    difficulty: "medium",
    points: 25,
    category: "food",
  },
  {
    id: "any-no-heat-complaints",
    city: "Any",
    title: "Heat Wave Hero",
    description: "Go 24 hours without complaining about the heat",
    difficulty: "hard",
    points: 50,
    category: "adventure",
  },
  {
    id: "any-cricket-vs-baseball",
    city: "Any",
    title: "Cricket Missionary",
    description: "Convince an American that cricket is better than baseball",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "any-new-food",
    city: "Any",
    title: "First Timer",
    description: "Eat something none of you have ever tried",
    difficulty: "medium",
    points: 25,
    category: "food",
  },
  {
    id: "any-match-friend",
    city: "Any",
    title: "International Friendship",
    description: "Make a friend from a different country at a match",
    difficulty: "medium",
    points: 25,
    category: "social",
  },
  {
    id: "any-sunset",
    city: "Any",
    title: "Golden Hour",
    description: "Find a viewpoint/rooftop and watch the sunset",
    difficulty: "medium",
    points: 25,
    category: "adventure",
  },
  {
    id: "any-photobomb-tv",
    city: "Any",
    title: "We're on TV!",
    description: "Photobomb a live TV broadcast at a match",
    difficulty: "legendary",
    points: 100,
    category: "dare",
  },
  {
    id: "any-flag-display",
    city: "Any",
    title: "Flag Bearers",
    description: "Display a flag from home at a match or sports bar",
    difficulty: "easy",
    points: 10,
    category: "culture",
  },
  {
    id: "any-three-lions",
    city: "Any",
    title: "Three Lions Choir",
    description: "Get a group of strangers to sing Three Lions with you",
    difficulty: "hard",
    points: 50,
    category: "social",
  },
  {
    id: "any-tip-master",
    city: "Any",
    title: "Tip Master",
    description: "Successfully calculate a 20% tip without a phone for 3 meals in a row",
    difficulty: "easy",
    points: 10,
    category: "dare",
  },
  {
    id: "any-local-recommendation",
    city: "Any",
    title: "Local's Choice",
    description: "Ask a local for their favourite hidden gem and actually go there",
    difficulty: "medium",
    points: 25,
    category: "adventure",
  },
];
